### ISSUE TITLE
mapcar: Symbol’s function definition is void: -zip

### ISSUE THREAD

**Issue by maciej-lech** [m0smith/annals#8]
Hi,

I get this error when I call `annals-task`.

Thanks in advance!
BR/ M

**Comment by m0smith** [comment]
Thanks for the comment.  I wasn't aware anyone else even knew of this project.  Let me know what features you would like to see.

Sorry for the delay in answering, my life has been a bit hectic.

-zip is in the dash package.  Just install it.

See https://github.com/magnars/dash.el
